export const allModels: string[] = [
    '01-ai/yi-large',
    'aetherwiing/mn-starcannon-12b',
    'agentica-org/deepcoder-14b-preview:free',
    'ai21/jamba-1-5-large',
    'ai21/jamba-1-5-mini',
    'ai21/jamba-1.6-large',
    'ai21/jamba-1.6-mini',
    'ai21/jamba-instruct',
    'aion-labs/aion-1.0',
    'aion-labs/aion-1.0-mini',
    'aion-labs/aion-rp-llama-3.1-8b',
    'alfredpros/codellama-7b-instruct-solidity',
    'all-hands/openhands-lm-32b-v0.1',
    'allenai/molmo-7b-d:free',
    'allenai/olmo-7b-instruct',
    'alpindale/goliath-120b',
    'alpindale/magnum-72b',
    'amazon/nova-lite-v1',
    'amazon/nova-micro-v1',
    'amazon/nova-pro-v1',
    'anthracite-org/magnum-v2-72b',
    'anthracite-org/magnum-v4-72b',
    'anthropic/claude-2',
    'anthropic/claude-2:beta',
    'anthropic/claude-2.0',
    'anthropic/claude-2.0:beta',
    'anthropic/claude-2.1',
    'anthropic/claude-2.1:beta',
    'anthropic/claude-3-haiku',
    'anthropic/claude-3-haiku:beta',
    'anthropic/claude-3-opus',
    'anthropic/claude-3-opus:beta',
    'anthropic/claude-3-sonnet',
    'anthropic/claude-3-sonnet:beta',
    'anthropic/claude-3.5-haiku',
    'anthropic/claude-3.5-haiku-20241022',
    'anthropic/claude-3.5-haiku-20241022:beta',
    'anthropic/claude-3.5-haiku:beta',
    'anthropic/claude-3.5-sonnet',
    'anthropic/claude-3.5-sonnet-20240620',
    'anthropic/claude-3.5-sonnet-20240620:beta',
    'anthropic/claude-3.5-sonnet:beta',
    'anthropic/claude-3.7-sonnet',
    'anthropic/claude-3.7-sonnet:beta',
    'anthropic/claude-3.7-sonnet:thinking',
    'arliai/qwq-32b-arliai-rpr-v1:free',
    'bytedance-research/ui-tars-72b:free',
    'cognitivecomputations/dolphin-mixtral-8x22b',
    'cognitivecomputations/dolphin3.0-mistral-24b:free',
    'cognitivecomputations/dolphin3.0-r1-mistral-24b:free',
    'cohere/command',
    'cohere/command-a',
    'cohere/command-r',
    'cohere/command-r-03-2024',
    'cohere/command-r-08-2024',
    'cohere/command-r-plus',
    'cohere/command-r-plus-04-2024',
    'cohere/command-r-plus-08-2024',
    'cohere/command-r7b-12-2024',
    'deepseek/deepseek-chat',
    'deepseek/deepseek-chat-v3-0324',
    'deepseek/deepseek-chat-v3-0324:free',
    'deepseek/deepseek-chat:free',
    'deepseek/deepseek-coder',
    'deepseek/deepseek-prover-v2',
    'deepseek/deepseek-prover-v2:free',
    'deepseek/deepseek-r1',
    'deepseek/deepseek-r1-distill-llama-70b',
    'deepseek/deepseek-r1-distill-llama-70b:free',
    'deepseek/deepseek-r1-distill-llama-8b',
    'deepseek/deepseek-r1-distill-qwen-1.5b',
    'deepseek/deepseek-r1-distill-qwen-14b',
    'deepseek/deepseek-r1-distill-qwen-14b:free',
    'deepseek/deepseek-r1-distill-qwen-32b',
    'deepseek/deepseek-r1-distill-qwen-32b:free',
    'deepseek/deepseek-r1-zero:free',
    'deepseek/deepseek-r1:free',
    'deepseek/deepseek-v3-base:free',
    'eleutherai/llemma_7b',
    'eva-unit-01/eva-llama-3.33-70b',
    'eva-unit-01/eva-qwen-2.5-32b',
    'eva-unit-01/eva-qwen-2.5-72b',
    'featherless/qwerky-72b:free',
    'google/gemini-2.0-flash-001',
    'google/gemini-2.0-flash-exp:free',
    'google/gemini-2.0-flash-lite-001',
    'google/gemini-2.5-flash-preview',
    'google/gemini-2.5-flash-preview:thinking',
    'google/gemini-2.5-pro-exp-03-25',
    'google/gemini-2.5-pro-preview-03-25',
    'google/gemini-flash-1.5',
    'google/gemini-flash-1.5-8b',
    'google/gemini-flash-1.5-8b-exp',
    'google/gemini-pro-1.5',
    'google/gemini-pro-vision',
    'google/gemma-2-27b-it',
    'google/gemma-2-9b-it',
    'google/gemma-2-9b-it:free',
    'google/gemma-3-12b-it',
    'google/gemma-3-12b-it:free',
    'google/gemma-3-1b-it:free',
    'google/gemma-3-27b-it',
    'google/gemma-3-27b-it:free',
    'google/gemma-3-4b-it',
    'google/gemma-3-4b-it:free',
    'google/learnlm-1.5-pro-experimental:free',
    'google/palm-2-chat-bison',
    'google/palm-2-chat-bison-32k',
    'google/palm-2-codechat-bison',
    'google/palm-2-codechat-bison-32k',
    'gryphe/mythomax-l2-13b',
    'huggingfaceh4/zephyr-7b-beta:free',
    'inception/mercury-coder-small-beta',
    'infermatic/mn-inferor-12b',
    'inflection/inflection-3-pi',
    'inflection/inflection-3-productivity',
    'jondurbin/airoboros-l2-70b',
    'latitudegames/wayfarer-large-70b-llama-3.3',
    'liquid/lfm-3b',
    'liquid/lfm-40b',
    'liquid/lfm-7b',
    'mancer/weaver',
    'meta-llama/llama-2-70b-chat',
    'meta-llama/llama-3-70b-instruct',
    'meta-llama/llama-3-8b-instruct',
    'meta-llama/llama-3.1-405b',
    'meta-llama/llama-3.1-405b-instruct',
    'meta-llama/llama-3.1-405b:free',
    'meta-llama/llama-3.1-70b-instruct',
    'meta-llama/llama-3.1-8b-instruct',
    'meta-llama/llama-3.1-8b-instruct:free',
    'meta-llama/llama-3.2-11b-vision-instruct',
    'meta-llama/llama-3.2-11b-vision-instruct:free',
    'meta-llama/llama-3.2-1b-instruct',
    'meta-llama/llama-3.2-1b-instruct:free',
    'meta-llama/llama-3.2-3b-instruct',
    'meta-llama/llama-3.2-3b-instruct:free',
    'meta-llama/llama-3.2-90b-vision-instruct',
    'meta-llama/llama-3.3-70b-instruct',
    'meta-llama/llama-3.3-70b-instruct:free',
    'meta-llama/llama-4-maverick',
    'meta-llama/llama-4-maverick:free',
    'meta-llama/llama-4-scout',
    'meta-llama/llama-4-scout:free',
    'meta-llama/llama-guard-2-8b',
    'meta-llama/llama-guard-3-8b',
    'meta-llama/llama-guard-4-12b',
    'microsoft/mai-ds-r1:free',
    'microsoft/phi-3-medium-128k-instruct',
    'microsoft/phi-3-mini-128k-instruct',
    'microsoft/phi-3.5-mini-128k-instruct',
    'microsoft/phi-4',
    'microsoft/phi-4-multimodal-instruct',
    'microsoft/phi-4-reasoning-plus:free',
    'microsoft/phi-4-reasoning:free',
    'microsoft/wizardlm-2-8x22b',
    'minimax/minimax-01',
    'mistral/ministral-8b', // Note: Likely a typo in original list, assuming mistralai/
    'mistralai/codestral-2501',
    'mistralai/codestral-mamba',
    'mistralai/ministral-3b', // Assuming mistralai/ prefix
    'mistralai/ministral-8b', // Assuming mistralai/ prefix
    'mistralai/mistral-7b-instruct',
    'mistralai/mistral-7b-instruct-v0.1',
    'mistralai/mistral-7b-instruct-v0.2',
    'mistralai/mistral-7b-instruct-v0.3',
    'mistralai/mistral-7b-instruct:free',
    'mistralai/mistral-large',
    'mistralai/mistral-large-2407',
    'mistralai/mistral-large-2411',
    'mistralai/mistral-medium',
    'mistralai/mistral-nemo',
    'mistralai/mistral-nemo:free',
    'mistralai/mistral-saba',
    'mistralai/mistral-small',
    'mistralai/mistral-small-24b-instruct-2501',
    'mistralai/mistral-small-24b-instruct-2501:free',
    'mistralai/mistral-small-3.1-24b-instruct',
    'mistralai/mistral-small-3.1-24b-instruct:free',
    'mistralai/mistral-tiny',
    'mistralai/mixtral-8x22b-instruct',
    'mistralai/mixtral-8x7b-instruct',
    'mistralai/pixtral-12b',
    'mistralai/pixtral-large-2411',
    'moonshotai/kimi-vl-a3b-thinking:free',
    'moonshotai/moonlight-16b-a3b-instruct:free',
    'neversleep/llama-3-lumimaid-70b',
    'neversleep/llama-3-lumimaid-8b',
    'neversleep/llama-3-lumimaid-8b:extended',
    'neversleep/llama-3.1-lumimaid-70b',
    'neversleep/llama-3.1-lumimaid-8b',
    'neversleep/noromaid-20b',
    'nothingiisreal/mn-celeste-12b',
    'nousresearch/deephermes-3-llama-3-8b-preview:free',
    'nousresearch/hermes-2-pro-llama-3-8b',
    'nousresearch/hermes-3-llama-3.1-405b',
    'nousresearch/hermes-3-llama-3.1-70b',
    'nousresearch/nous-hermes-2-mixtral-8x7b-dpo',
    'nvidia/llama-3.1-nemotron-70b-instruct',
    'nvidia/llama-3.1-nemotron-ultra-253b-v1:free',
    'nvidia/llama-3.3-nemotron-super-49b-v1',
    'nvidia/llama-3.3-nemotron-super-49b-v1:free',
    'open-r1/olympiccoder-32b:free',
    'openai/chatgpt-4o-latest', // Note: Specific version aliases might change
    'openai/gpt-3.5-turbo',
    'openai/gpt-3.5-turbo-0125',
    'openai/gpt-3.5-turbo-0613',
    'openai/gpt-3.5-turbo-1106',
    'openai/gpt-3.5-turbo-16k',
    'openai/gpt-3.5-turbo-instruct',
    'openai/gpt-4',
    'openai/gpt-4-0314', // Older snapshot
    'openai/gpt-4-1106-preview', // Older preview alias
    'openai/gpt-4-32k', // Older model
    'openai/gpt-4-32k-0314', // Older snapshot
    'openai/gpt-4-turbo', // Alias, points to newer turbo version
    'openai/gpt-4-turbo-preview', // Older preview alias
    'openai/gpt-4.1', // Potential future/internal model
    'openai/gpt-4.1-mini', // Potential future/internal model
    'openai/gpt-4.1-nano', // Potential future/internal model
    'openai/gpt-4.5-preview', // Potential future/internal model
    'openai/gpt-4o',
    'openai/gpt-4o-2024-05-13', // Specific snapshot
    'openai/gpt-4o-2024-08-06', // Specific snapshot
    'openai/gpt-4o-2024-11-20', // Specific snapshot
    'openai/gpt-4o-mini',
    'openai/gpt-4o-mini-2024-07-18', // Specific snapshot
    'openai/gpt-4o-mini-search-preview', // Preview
    'openai/gpt-4o-search-preview', // Preview
    'openai/gpt-4o:extended', // Potential future/internal model
    'openai/o1', // Potential future/internal model
    'openai/o1-mini', // Potential future/internal model
    'openai/o1-mini-2024-09-12', // Specific snapshot
    'openai/o1-preview', // Preview
    'openai/o1-preview-2024-09-12', // Specific snapshot
    'openai/o1-pro', // Potential future/internal model
    'openai/o3', // Potential future/internal model
    'openai/o3-mini', // Potential future/internal model
    'openai/o3-mini-high', // Potential future/internal model
    'openai/o4-mini', // Potential future/internal model
    'openai/o4-mini-high', // Potential future/internal model
    'opengvlab/internvl3-14b:free',
    'opengvlab/internvl3-2b:free',
    'openrouter/auto', // Special routing model
    'perplexity/llama-3.1-sonar-large-128k-online',
    'perplexity/llama-3.1-sonar-small-128k-online',
    'perplexity/r1-1776',
    'perplexity/sonar', // Alias
    'perplexity/sonar-deep-research',
    'perplexity/sonar-pro',
    'perplexity/sonar-reasoning',
    'perplexity/sonar-reasoning-pro',
    'pygmalionai/mythalion-13b',
    'qwen/qwen-2-72b-instruct',
    'qwen/qwen-2.5-72b-instruct',
    'qwen/qwen-2.5-72b-instruct:free',
    'qwen/qwen-2.5-7b-instruct',
    'qwen/qwen-2.5-7b-instruct:free',
    'qwen/qwen-2.5-coder-32b-instruct',
    'qwen/qwen-2.5-coder-32b-instruct:free',
    'qwen/qwen-2.5-vl-72b-instruct',
    'qwen/qwen-2.5-vl-7b-instruct',
    'qwen/qwen-2.5-vl-7b-instruct:free',
    'qwen/qwen-max', // Alias
    'qwen/qwen-plus', // Alias
    'qwen/qwen-turbo', // Alias
    'qwen/qwen-vl-max', // Alias
    'qwen/qwen-vl-plus', // Alias
    'qwen/qwen2.5-coder-7b-instruct',
    'qwen/qwen2.5-vl-32b-instruct',
    'qwen/qwen2.5-vl-32b-instruct:free',
    'qwen/qwen2.5-vl-3b-instruct:free',
    'qwen/qwen2.5-vl-72b-instruct',
    'qwen/qwen2.5-vl-72b-instruct:free',
    'qwen/qwen3-0.6b-04-28:free',
    'qwen/qwen3-1.7b:free',
    'qwen/qwen3-14b',
    'qwen/qwen3-14b:free',
    'qwen/qwen3-235b-a22b',
    'qwen/qwen3-235b-a22b:free',
    'qwen/qwen3-30b-a3b',
    'qwen/qwen3-30b-a3b:free',
    'qwen/qwen3-32b',
    'qwen/qwen3-32b:free',
    'qwen/qwen3-4b:free',
    'qwen/qwen3-8b',
    'qwen/qwen3-8b:free',
    'qwen/qwq-32b',
    'qwen/qwq-32b-preview',
    'qwen/qwq-32b-preview:free',
    'qwen/qwq-32b:free',
    'raifle/sorcererlm-8x22b',
    'rekaai/reka-flash-3:free',
    'sao10k/fimbulvetr-11b-v2',
    'sao10k/l3-euryale-70b',
    'sao10k/l3-lunaris-8b',
    'sao10k/l3.1-euryale-70b',
    'sao10k/l3.3-euryale-70b',
    'scb10x/llama3.1-typhoon2-70b-instruct',
    'scb10x/llama3.1-typhoon2-8b-instruct',
    'shisa-ai/shisa-v2-llama3.3-70b:free',
    'sophosympatheia/midnight-rose-70b',
    'steelskull/l3.3-electra-r1-70b',
    'thedrummer/anubis-pro-105b-v1',
    'thedrummer/rocinante-12b',
    'thedrummer/skyfall-36b-v2',
    'thedrummer/unslopnemo-12b',
    'thudm/glm-4-32b',
    'thudm/glm-4-32b:free',
    'thudm/glm-4-9b:free',
    'thudm/glm-z1-32b',
    'thudm/glm-z1-32b:free',
    'thudm/glm-z1-9b:free',
    'thudm/glm-z1-rumination-32b',
    'tngtech/deepseek-r1t-chimera:free',
    'undi95/remm-slerp-l2-13b',
    'undi95/toppy-m-7b',
    'x-ai/grok-2-1212',
    'x-ai/grok-2-vision-1212',
    'x-ai/grok-3-beta',
    'x-ai/grok-3-mini-beta',
    'x-ai/grok-beta',
    'x-ai/grok-vision-beta',
  ];
  